### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by indskgit** [indskgit/Plant_Disease_And_Plant_Identification#2]
Make better UI design for Camera or at detection Page.
![detection](https://user-images.githubusercontent.com/88468596/229429054-a5856b21-c97a-44fa-ac15-388f2363f71d.jpg)

**Comment by geekanonymous98** [comment]
hello sir, i want to work on this
plz assign it me.

**Comment by indskgit** [comment]
sure, start work on this.
for any guidence contact @indskgit or @Anand-Singh-techie
